import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { checkMutationIntegrity } from "./galtea-integrity.mjs";

const directory = fileURLToPath(new URL("../galtea-results.local/", import.meta.url));
const load = name => JSON.parse(readFileSync(`${directory}${name}.json`, "utf8"));
const escape = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
const manifest = load("manifest");
const round2 = process.argv.includes("--round2") ? load("round2-summary") : null;
const outputName = round2 ? "submission-round2" : "submission";
const before = load("before-runs").filter(run => run.suite === "integrity");
const after = load("after-fixed-runs").filter(run => run.suite === "integrity");
const holdoutBefore = load("holdout-before-runs"), holdoutAfter = load("holdout-after-runs");
const score = runs => `${runs.filter(run => checkMutationIntegrity(run).score === 1).length}/${runs.filter(run => checkMutationIntegrity(run).applicable).length}`;
const errors = runs => runs.filter(run => run.applicationError).length;
const demoId = "testCase_d07ehqfsqs7icsxffpv0mqa3";
const demoBefore = before.find(run => run.testCaseId === demoId), demoAfter = after.find(run => run.testCaseId === demoId);
if (!demoBefore || !demoAfter) throw new Error("The demo case needs both real provider runs");
const rows = before.map(run => {
  const rerun = after.find(next => next.testCaseId === run.testCaseId);
  return `<tr><td>${escape(run.testCaseId)}</td><td>${checkMutationIntegrity(run).score === 1 ? "Pass" : "Lost edits"}</td><td>${rerun ? checkMutationIntegrity(rerun).score === 1 ? "Pass" : "Failed" : "Not run"}</td></tr>`;
}).join("");
const evaluations = load("after-fixed-evaluations");
const integrityMetric = manifest.suites.find(suite => suite.key === "integrity").metricId;
const llmRows = evaluations.filter(row => row.metricId === integrityMetric);
const summary = {
  title: "Kan: the AI said done, but its edits undid each other",
  productId: manifest.productId,
  claim: "Compound canvas edits were generated correctly but executed from stale per-shape snapshots, silently losing earlier changes.",
  discovery: { before: score(before), after: score(after), cases: before.length },
  heldOut: { before: score(holdoutBefore), after: score(holdoutAfter), cases: holdoutBefore.length },
  executionErrors: { before: errors(before), after: errors(after), heldOutBefore: errors(holdoutBefore), heldOutAfter: errors(holdoutAfter) },
  broaderLlmJudge: { passedAtOne: llmRows.filter(row => row.status === "SUCCESS" && row.score === 1).length, total: llmRows.length, note: "Broader behavior metric; not equivalent to deterministic batch integrity. Judge explanations need review." },
  versions: { before: manifest.before, after: manifest["after-fixed"], holdoutBefore: manifest["holdout-before"], holdoutAfter: manifest["holdout-after"] },
  model: [...new Set([...before, ...after, ...holdoutBefore, ...holdoutAfter].map(run => run.model))],
  verification: { desktopTests: "90 passed", typecheck: "Desktop TypeScript passed", native: "Real Tauri WKWebView + Rust ACP + real provider + local transport + tldraw", additionalDrawingSuite: "Attempted after evaluation; unavailable because the QA app had exited. Not counted as passing.", backendOrMultiUser: "Not run for this offline-executor evaluation" },
  limitations: ["Synthetic offline-canvas evaluation; not live multi-user room coverage.", "The before visual is a replay of an actually recorded provider response against the archived original executor. After visual is a fresh real-provider run.", "The executor fix landed in parallel development while evaluation was in progress; it was preserved and independently verified, not credited as a new change by this evaluator.", "No claim that ambiguous meeting decisions or every requested layout operation are now correct.", "One of the six unseen after-fix runs returned unusable structured model output. It remains a failure in the reported first-pass results; it was not silently retried or excluded.", "The interrupted cached-module run is excluded and preserved in excluded-runs.json.", "The generated holdout did not follow the requested mix of simple controls; it is six additional compound-edit cases, not benign-control coverage."],
  remaining: ["Complete the mandatory Galtea product-feedback survey.", "Submit the evidence through the organizer's specified channel before their deadline."],
};
if (round2) summary.round2 = round2;
const round2Section = round2 ? `<h2>Round 2: broader request-level checks</h2><p>Twenty curated regression cases, five per category, with 30 actual turns per executor. These are not claimed to be newly Galtea-generated prompts. Multi-turn cases preserve both native canvas state and real conversation entries between turns.</p><table><thead><tr><th>Category</th><th>Captured original executor</th><th>Fixed executor</th></tr></thead><tbody>${["ordinary", "compound", "protection", "conversation"].map(category => { const a = round2.versions["round2-before"].categories[category], b = round2.versions["round2-after"].categories[category]; return `<tr><td>${escape(category)}</td><td>${a.passed}/${a.total}</td><td>${b.passed}/${b.total}</td></tr>`; }).join("")}</tbody></table><p>These stronger checks use expected outcomes declared before execution, not the model's emitted operations: requested values, stable IDs, unrelated content and positions, connection endpoints, and all intermediate turns. Any failed turn fails its conversation. The baseline and fixed runs use the same model; only the frozen executor differs. The LLM judge scored ${round2.versions["round2-before"].judge.passedAtOne}/${round2.versions["round2-before"].judge.total} before and ${round2.versions["round2-after"].judge.passedAtOne}/${round2.versions["round2-after"].judge.total} after; it missed some state failures, so the table uses deterministic checks. One baseline protection failure was malformed model output, not a lost canvas write: its improvement must not be attributed solely to the executor fix.</p><h3>Three separately reported malformed-output repeats</h3><p>${round2.versions["round2-repeats"].passed}/${round2.versions["round2-repeats"].total} repeats satisfied the complete request. ${round2.versions["round2-repeats"].errors.length} reported execution/format errors. These repeats do not replace the original held-out failure or count toward the 20-case first-pass scores.</p><details><summary>Remaining Round 2 failures and execution errors</summary><pre>${escape(JSON.stringify({ after: round2.versions["round2-after"].failures, errors: round2.versions["round2-after"].errors, repeats: round2.versions["round2-repeats"].failures }, null, 2))}</pre></details><p><a href="submission.html">Original Round 1 evidence, unchanged</a>. Galtea versions: <strong>kan-round2-before-2026-09-20</strong>, <strong>kan-round2-after-2026-09-20</strong>, and <strong>kan-round2-repeats-2026-09-20</strong>.</p>` : "";
writeFileSync(`${directory}${outputName}.json`, JSON.stringify(summary, null, 2));
writeFileSync(`${directory}${outputName}.html`, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>${escape(summary.title)}</title><style>body{font:17px/1.55 system-ui,sans-serif;max-width:1100px;margin:48px auto;padding:0 24px;color:#18212f;background:#fafafa}h1{font-size:40px;line-height:1.12}h2{margin-top:36px}table{border-collapse:collapse;width:100%;background:white}td,th{border:1px solid #d8dee8;padding:10px;text-align:left}img{width:100%;border:1px solid #d8dee8;border-radius:8px}pre{white-space:pre-wrap;padding:20px;background:#eef1f6;overflow-wrap:anywhere}small{color:#475569}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}.number{font-size:30px;font-weight:700}@media(max-width:800px){.pair{grid-template-columns:1fr}}@media print{body{margin:0}details{display:block}}</style><main>
<h1>${escape(summary.title)}</h1><p><strong>Find → Fix → Prove</strong> · Galtea hackathon evidence · Synthetic data only</p>
<p>Kan helps teams turn conversations into shared canvas content. Galtea generated requests combining a label change, color change, connection and preservation constraints. The agent produced the right operations, but the application silently overwrote earlier changes while reporting completion.</p>
<h2>What a real user sees</h2><pre>${escape(demoBefore.input)}</pre><p>Before: the requested blue rectangle stayed red. In more complex cases, labels and legal-review notes also reverted to their old contents. This can leave a shared decision board contradicting the requested update while the assistant says it is done.</p>
<div class="pair"><section><h3>Before — recorded-response replay</h3><img src="before-replay-${demoId}.png" alt="Original executor leaves the launch rectangle red despite a blue style operation"><small>Real WKWebView. Exact recorded operation batch replayed against the captured original executor; not a fresh provider call.</small></section><section><h3>After — fresh real-provider run</h3><img src="after-fixed-${demoId}.png" alt="Fixed executor retains both the blue color and updated label"><small>Same generated test case, same provider/model, same synthetic starting canvas.</small></section></div>
<h2>Root cause and fix</h2><p>The old batch planner read each operation from the original canvas snapshot. A label update carried the original color; a later arrangement carried the original label and card contents. Applying these whole-shape records discarded earlier writes. The fixed planner reads the most recent staged shape and emits one final record per shape before committing the batch.</p><p>The fix landed in parallel development during discovery. We preserved that work, reproduced seven regression failures against the archived old code, and verified that all eight batch regression tests pass with the current implementation.</p>
<h2>Measured evidence</h2><table><thead><tr><th>Deterministic applied-field integrity</th><th>Before</th><th>After</th></tr></thead><tbody><tr><td>Original ${before.length} editing cases</td><td>${score(before)}</td><td>${score(after)}</td></tr><tr><td>${holdoutBefore.length} unseen generated compound-edit cases</td><td>${score(holdoutBefore)}</td><td>${score(holdoutAfter)}</td></tr></tbody></table><p>This metric checks that emitted label, color and card-content edits survive application. It does not substitute for testing whether the agent chose the right edits. Scores are uploaded to Galtea as a self-hosted metric; a separate Galtea LLM judge evaluates broader intent compliance. That broader judge scored ${summary.broaderLlmJudge.passedAtOne}/${summary.broaderLlmJudge.total} rerun cases at 1.0: this is not a claim of perfect overall task success.</p>
<p>Execution errors: original before ${errors(before)}, original after ${errors(after)}, unseen before ${errors(holdoutBefore)}, unseen after ${errors(holdoutAfter)}. Model: ${escape(summary.model.join(", "))}.</p>
<h2>Galtea results</h2><p><a href="https://platform.galtea.ai/product/${escape(manifest.productId)}">Open the Galtea product</a>. Compare <strong>kan-before-2026-09-20</strong> with <strong>kan-after-fixed-2026-09-20</strong>. Use the metric <strong>Kan: batch edits survive execution (deterministic)</strong>. The held-out versions are <strong>kan-holdout-before-2026-09-20</strong> and <strong>kan-holdout-after-2026-09-20</strong>.</p>
<details><summary>Original editing cases</summary><table><thead><tr><th>Galtea case ID</th><th>Before</th><th>After</th></tr></thead><tbody>${rows}</tbody></table></details>
${round2Section}
<h2>Reproducibility and limits</h2><ul>${summary.limitations.map(item => `<li>${escape(item)}</li>`).join("")}</ul><p>Local artifacts include the generated cases, immutable baseline source capture, raw native outputs, executor fingerprints, screenshots, original judge explanations, and the regression tests. No API keys or real meeting content are included.</p>
<h2>Feedback notes for the mandatory survey</h2><ul><li>Useful: generated compound requests uncovered a visible execution failure that checking the model response alone would miss. CLI ingestion let a native desktop app be evaluated without publishing an API.</li><li>Needs improvement: custom generation instructions were not consistently followed; the requested mix of simple controls became more approval-themed compound cases.</li><li>Needs improvement: some LLM-judge explanations confused proposed operations with final state and returned fractional scores for a binary rubric. Deterministic checks made the evidence reliable.</li></ul>
<h2>Still required to qualify</h2><p>Complete the mandatory product-feedback survey yourself and submit through the organizer's chosen channel. This evidence pack does not claim those steps are complete.</p>
</main></html>`);
console.log(JSON.stringify(summary, null, 2));
console.log(`${directory}${outputName}.html`);
